// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://keikssvjmvtdorueoibj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtlaWtzc3ZqbXZ0ZG9ydWVvaWJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NDc0NDcsImV4cCI6MjA2NDEyMzQ0N30.cDprszIsLwW8t6YklF-H6z4UKDICTwbjyIzsnYPHbWI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);