
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxifiwzklvnceyhtmvkb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4aWZpd3prbHZuY2V5aHRtdmtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxOTc0NjUsImV4cCI6MjA1NTc3MzQ2NX0.uoJqyke36nO5ymtEUBXsjhP5-nJlDq_COpbrHKr6cQQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      storage: localStorage
    }
  }
);
